export const SET_VIDEOS = "SET_VIDEOS";
export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const TOGGLE_VIDEO_FETCHING_STATE = "TOGGLE_VIDEO_FETCHING_STATE";
export const TOGGLE_PLAYLIST_FETCHING_STATE = "TOGGLE_PLAYLIST_FETCHING_STATE";
export const TOGGLE_CURRENT_VIDEO_FETCHING_STATE =
  "TOGGLE_CURRENT_VIDEO_FETCHING_STATE";
export const TOGGLE_AUTH_STATE = "TOGGLE_AUTH_STATE";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_CURRENT_VIDEO = "SET_CURRENT_VIDEO";
export const SET_COMMENTS = "SET_COMMENTS";
